name: release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "release version"
        required: true

env:
  RELEASE: ${{ github.event.inputs.release }}
  GITHUB_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.17"

      - name: build releases
        run: |
          sudo chmod 755 ./bin/release.sh
          ./bin/release.sh ${{ env.RELEASE }}
